---
- name: Add docker.com repository
  apt_repository:
    repo: deb https://get.docker.com/ubuntu docker main
    state: present

- name: Add repository key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id={{ docker_repository_gpg }}
    state=present
#  command: "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys {{ docker_repository_gpg }}"

- name: Reload apt cache
  apt: update_cache=yes

- name: Install docker requirements
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items: "{{ required_packages }}"

- name: Install docker
  apt: name=lxc-docker state=latest update_cache=yes cache_valid_time=3600

- name: Create docker base dir
  file:
    path={{ docker_base_dir }}
    owner=root
    group=docker
    state=directory
    mode="2770"

- name: Copy /etc/default/docker
  template:
    src=etc-default-docker.j2
    dest=/etc/default/docker
    owner=root
    group=root
    mode=0644
  notify: restart docker
